[book]
authors = ["xmdhs"]
language = "en"
multilingual = false
src = "src"
title = "积分统计"

[output.html]
#site-url = "/"

[output.html.search]
enable = false

[output.html.fold]
enable = true
level = 0